# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Radicalize < Formula
  desc "Migrate existing local and remote git repos to Radical"
  homepage "https://github.com/stevedylandev/radicalize"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stevedylandev/radicalize/releases/download/v1.0.0/radicalize_Darwin_x86_64.tar.gz"
      sha256 "fb27a86737c2dad3d75596af41a596bad12cdd6b4670f5e5444899c53c7cb07f"

      def install
        bin.install "radicalize"
      end
    end
    on_arm do
      url "https://github.com/stevedylandev/radicalize/releases/download/v1.0.0/radicalize_Darwin_arm64.tar.gz"
      sha256 "779108276c185e90d425714351953c5622f1e2041607f3a9c0ad400f71ab2e60"

      def install
        bin.install "radicalize"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stevedylandev/radicalize/releases/download/v1.0.0/radicalize_Linux_x86_64.tar.gz"
        sha256 "d3e46fecc375d0c7032866dc8e74292992235e5dba11586dfb0138849f6c1885"

        def install
          bin.install "radicalize"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stevedylandev/radicalize/releases/download/v1.0.0/radicalize_Linux_arm64.tar.gz"
        sha256 "a6f9c13ef762f1871779e88d6c58a475ccb8ebd953025d38a6b6c58a74efee75"

        def install
          bin.install "radicalize"
        end
      end
    end
  end
end
