# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Radicalize < Formula
  desc "Migrate existing local and remote git repos to Radicle"
  homepage "https://github.com/stevedylandev/radicalize"
  version "1.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stevedylandev/radicalize/releases/download/v1.0.1/radicalize_Darwin_x86_64.tar.gz"
      sha256 "b87f32b25bf7d1a84055254bc9f5799d5a6b2ac23ef5095ea07a663812c84115"

      def install
        bin.install "radicalize"
      end
    end
    on_arm do
      url "https://github.com/stevedylandev/radicalize/releases/download/v1.0.1/radicalize_Darwin_arm64.tar.gz"
      sha256 "420709d2e59a20e8b65c09030aadcc4867edfe48407281c35bb8efca6d335fca"

      def install
        bin.install "radicalize"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stevedylandev/radicalize/releases/download/v1.0.1/radicalize_Linux_x86_64.tar.gz"
        sha256 "fb6818289074ae233a6e700f83c5a013e143570441bee35092583ed5e61b921b"

        def install
          bin.install "radicalize"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stevedylandev/radicalize/releases/download/v1.0.1/radicalize_Linux_arm64.tar.gz"
        sha256 "2d9ba5a3b2226a93810f769b80c9261f421d15a07b62c45c3ce973a9c39c93aa"

        def install
          bin.install "radicalize"
        end
      end
    end
  end
end
