# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Radicalize < Formula
  desc "Migrate existing local git repos to Radical"
  homepage "https://github.com/stevedylandev/radicalize"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stevedylandev/radicalize/releases/download/v0.1.0/radicalize_Darwin_x86_64.tar.gz"
      sha256 "52333105c0f7a74a6363a1e573e841fbef079235e00f2766495e0d7b851534c5"

      def install
        bin.install "radicalize"
      end
    end
    on_arm do
      url "https://github.com/stevedylandev/radicalize/releases/download/v0.1.0/radicalize_Darwin_arm64.tar.gz"
      sha256 "1240761ff730b85e218884dbd76c6214c45e6b7fc2a805d2cddf0f9bdf925725"

      def install
        bin.install "radicalize"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stevedylandev/radicalize/releases/download/v0.1.0/radicalize_Linux_x86_64.tar.gz"
        sha256 "3404c1f4da20307f5f5acab60b996ec0da40a7936bd6cb8e8898f80c51685082"

        def install
          bin.install "radicalize"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stevedylandev/radicalize/releases/download/v0.1.0/radicalize_Linux_arm64.tar.gz"
        sha256 "9a77a21ed6b02d6e7a75eb2ce2ee4c812b855b2f4988989e654e9e86c16d23b1"

        def install
          bin.install "radicalize"
        end
      end
    end
  end
end
